modLoader="javafml"
loaderVersion="[${loader_version},)"
license="All rights reserved"
issueTrackerURL="https://github.com/MeinKraft/Crimson-Blood-Melons/issues" #optional

[[mods]]
modId="crimsonbloodmelons"
version="${version}"
displayName="Crimson Blood Melons"
displayURL="https://www.curseforge.com/minecraft/mc-mods/crimson-blood-melons"
updateJSONURL = "https://github.com/MeinKraft/Crimson-Blood-Melons/raw/main/update.json"
authors="§4Crimson_Fluff"
logoFile="logo.png" #optional
credits="\n§bTechnovision§r for his awesome modding YouTube series\n§bTurtyWurty§r for his awesome modding YouTube series" #optional
description=''' "Melons that steal your soul... well your blood at least" '''

[[dependencies.crimsonbloodmelons]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    side="BOTH"
[[dependencies.crimsonbloodmelons]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    side="BOTH"
